### ISSUE TITLE
Defect in map in operator++

### ISSUE THREAD

**Issue by gitbaum** [ibr-alg/wiselib#4] opened 2011-10-12 10:45 UTC
when calling map[key]++ (with int values in the map), the value is not incremented. is this a defect? does this really happen?

Check again!

**Comment by Droggelbecher** [comment] 2011-10-12 11:48
which map does this refer to? map_list or map_static_vector?

**Comment by gitbaum** [comment] 2011-10-12 13:10
afaik that happened in the map_static_vector

**Comment by shubhamsomani** [comment] 2013-02-08 07:49
I checked out this issue and tried post increment operator on map_static_vector. It works fine for me.
Please see http://www.flickr.com/photos/93013264@N03/8454486177/in/photostream for details.

**Comment by Droggelbecher** [comment] 2013-02-10 10:44
Thanks shubhamsomani for testing.
I'm closing this as I know of nobody who can reproduce this, also since the opening of this bug there
where commits affecting operator[], so it might have been fixed as a side-effect meanwhile.

If somebody encounters this (or another) problem, dont hesitate to open a new issue.

**Closed as completed by Droggelbecher** 2013-02-10 10:44 UTC
Labels: Data Structures
